name: Update Deployment Repo
description: "Updates application in the deployment"
inputs:
  kebab:
    required: true
    description: bebab-case value.
  other:
    required: false
    description: "whatever"
    default: "default value"
runs:
  using: composite
  steps:
    - name: Convert
      shell: bash
      run: |
        echo "${{ inputs.other }}"
        APPLICATION_CAMEL_CASE="$(sed -E 's/-([a-z])/\U\1/g' <<< ${{ inputs.kebab }})"
        echo "===="
        echo "app: $APPLICATION_CAMEL_CASE"
