name: Update Deployment Repo
description: "Updates application in the deployment"
inputs:
  kebab:
    required: true
    description: bebab-case value.
runs:
  using: composite
  steps:
    - name: Convert
      shell: bash
      run: |
        sed -E 's/_([a-z])/\U\1/g' <<< ${{ inputs.kebab }}
