name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  Publish:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-case
        with:
          kebab: "my_long_var"
